'useTabs': true
'tabWidth': 2
'printWidth': 80
'singleQuote': true
'semi': false
'trailingComma': 'all'
'arrowParens': 'avoid'
'endOfLine': 'auto'
'importOrder': ['^@/(.*)$', '^[./]']
'importOrderSeparation': true
'importOrderSortSpecifiers': true
'importOrderParserPlugins': ['typescript', 'jsx', 'decorators-legacy']
