export const ACTIONS = {
	DOWNLOAD_COURSE: 'DOWNLOAD_COURSE',
	DOWNLOAD_SECTION: 'DOWNLOAD_SECTION',
	DOWNLOAD_VIDEO: 'DOWNLOAD_VIDEO',
	PAUSE_COURSE: 'PAUSE_COURSE',
	PAUSE_SECTION: 'PAUSE_SECTION',
	PAUSE_VIDEO: 'PAUSE_VIDEO',
	RESUME_COURSE: 'RESUME_COURSE',
	RESUME_SECTION: 'RESUME_SECTION',
	RESUME_VIDEO: 'RESUME_VIDEO',
	CANCEL_COURSE: 'CANCEL_COURSE',
	CANCEL_SECTION: 'CANCEL_SECTION',
	CANCEL_VIDEO: 'CANCEL_VIDEO',
} as const

export const MESSAGES = {
	PARSE_COURSE: 'PARSE_COURSE',
	PARSE_VIDEO_ID: 'PARSE_VIDEO_ID',
} as const

export const BACKGROUND_ACTIONS = {
	DOWNLOAD: 'download',
	DOWNLOAD_SYNC: 'download-sync',
	BADGE: 'badge',
} as const

// TODO:
//export const COURSE_TYPES = {
//  NEW: 'NEW',
//  OLD: 'OLD',
//} as const
//
